import { StyleSheet } from 'react-native';

import { MW_COLORS, MW_FONTS, MW_TYPE } from '@/constants/morgan-theme';

/** Shared validation-section chrome — Minimalist Monochrome. */
export const chipiBaseStyles = StyleSheet.create({
  section: {
    padding: 16,
    marginBottom: 16,
    backgroundColor: MW_COLORS.card,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: MW_COLORS.border,
  },
  kicker: {
    fontSize: MW_TYPE.kicker,
    fontWeight: '600',
    color: MW_COLORS.mutedForeground,
    marginBottom: 4,
    letterSpacing: 2.2,
    textTransform: 'uppercase',
    fontFamily: MW_FONTS.mono,
  },
  hook: {
    fontSize: MW_TYPE.label,
    fontWeight: '700',
    color: MW_COLORS.foreground,
    marginBottom: 8,
    fontFamily: MW_FONTS.bodySemi,
  },
  subtitle: {
    fontSize: MW_TYPE.bodySm,
    color: MW_COLORS.mutedForeground,
    marginBottom: 12,
    fontFamily: MW_FONTS.body,
    lineHeight: 22,
  },
  note: {
    fontSize: MW_TYPE.bodySm,
    color: MW_COLORS.mutedForeground,
    marginBottom: 12,
    fontFamily: MW_FONTS.body,
    lineHeight: 20,
  },
  body: {
    fontSize: MW_TYPE.label,
    color: MW_COLORS.mutedForeground,
    marginBottom: 12,
    lineHeight: 20,
    fontFamily: MW_FONTS.body,
  },
  muted: {
    color: MW_COLORS.mutedForeground,
    fontFamily: MW_FONTS.body,
  },
  label: {
    fontSize: MW_TYPE.label,
    fontWeight: '600',
    marginBottom: 6,
    color: MW_COLORS.mutedForeground,
    fontFamily: MW_FONTS.bodySemi,
  },
  rowLabel: {
    fontSize: MW_TYPE.label,
    fontWeight: '600',
    color: MW_COLORS.mutedForeground,
    fontFamily: MW_FONTS.bodySemi,
  },
  fieldLabel: {
    fontSize: MW_TYPE.kicker,
    fontWeight: '700',
    color: MW_COLORS.mutedForeground,
    fontFamily: MW_FONTS.mono,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  error: {
    color: MW_COLORS.foreground,
    fontSize: MW_TYPE.bodySm,
    marginTop: 8,
    fontFamily: MW_FONTS.body,
    fontStyle: 'italic',
    borderLeftWidth: 4,
    borderLeftColor: MW_COLORS.foreground,
    paddingLeft: 10,
  },
  mono: {
    fontFamily: MW_FONTS.mono,
    fontSize: MW_TYPE.mono,
    color: MW_COLORS.foreground,
  },
  address: {
    fontFamily: MW_FONTS.mono,
    fontSize: MW_TYPE.mono,
    marginTop: 16,
    color: MW_COLORS.foreground,
  },
  input: {
    borderWidth: 0,
    borderBottomWidth: 2,
    borderBottomColor: MW_COLORS.border,
    paddingVertical: 12,
    paddingHorizontal: 0,
    fontSize: MW_TYPE.bodySm,
    backgroundColor: MW_COLORS.background,
    color: MW_COLORS.foreground,
    marginBottom: 12,
    fontFamily: MW_FONTS.body,
  },
  primaryButton: {
    backgroundColor: MW_COLORS.foreground,
    borderRadius: 0,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: MW_COLORS.foreground,
  },
  primaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButtonText: {
    color: MW_COLORS.accentForeground,
    fontWeight: '600',
    fontSize: MW_TYPE.label,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    fontFamily: MW_FONTS.mono,
  },
  secondaryButton: {
    backgroundColor: MW_COLORS.background,
    borderRadius: 0,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: MW_COLORS.border,
  },
  secondaryButtonText: {
    color: MW_COLORS.foreground,
    fontWeight: '700',
    fontSize: MW_TYPE.label,
    fontFamily: MW_FONTS.mono,
    letterSpacing: 0.6,
  },
  link: {
    fontSize: MW_TYPE.bodySm,
    color: MW_COLORS.foreground,
    fontWeight: '700',
    fontFamily: MW_FONTS.bodySemi,
    textDecorationLine: 'underline',
  },
  card: { gap: 10 },
  row: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center' },
  valueLarge: {
    fontSize: 16,
    color: MW_COLORS.foreground,
    fontFamily: MW_FONTS.bodySemi,
  },
  /** Inline metric next to a row label (balance, flags). */
  metricValue: {
    fontSize: 17,
    color: MW_COLORS.foreground,
    fontFamily: MW_FONTS.bodySemi,
  },
  short: {
    fontSize: 13,
    color: MW_COLORS.mutedForeground,
    marginTop: 4,
    fontFamily: MW_FONTS.body,
  },
  field: { marginBottom: 12 },
  spinner: { marginVertical: 12 },
  hookTight: {
    fontSize: MW_TYPE.label,
    fontWeight: '700',
    color: MW_COLORS.foreground,
    marginBottom: 12,
    fontFamily: MW_FONTS.bodySemi,
  },
  mutedBlock: {
    color: MW_COLORS.mutedForeground,
    marginBottom: 8,
    fontFamily: MW_FONTS.body,
  },
  ghostLinkButton: {
    marginTop: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  ghostLinkText: {
    color: MW_COLORS.foreground,
    fontWeight: '600',
    fontFamily: MW_FONTS.bodySemi,
    textDecorationLine: 'underline',
  },
  balanceValue: {
    color: MW_COLORS.foreground,
    fontSize: 32,
    fontWeight: '700',
    fontFamily: MW_FONTS.display,
    letterSpacing: -0.5,
  },
  balanceLabel: {
    color: MW_COLORS.mutedForeground,
    fontSize: MW_TYPE.kicker,
    fontFamily: MW_FONTS.mono,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  meta: {
    fontSize: MW_TYPE.bodySm,
    color: MW_COLORS.mutedForeground,
    fontFamily: MW_FONTS.body,
  },
  txRow: {
    padding: 10,
    backgroundColor: MW_COLORS.background,
    borderRadius: 0,
    borderWidth: 1,
    borderColor: MW_COLORS.border,
    gap: 4,
  },
  txType: {
    fontWeight: '700',
    color: MW_COLORS.foreground,
    fontFamily: MW_FONTS.bodySemi,
  },
  txStatus: {
    fontSize: MW_TYPE.kicker,
    color: MW_COLORS.mutedForeground,
    fontFamily: MW_FONTS.mono,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
});
